use_frameworks!

target 'ZJPictureBrowser_Example' do
  pod 'ZJPictureBrowser', :path => '../'

  target 'ZJPictureBrowser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
